In [115]:
import numpy as np


2: Create an array of 10 zeros# np.zeros

In [116]:
array = np.zeros(10)
print(array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3: Create an array of 10 ones

In [117]:
array_of_ones = np.ones(10)
print(array_of_ones)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


4: Create an array of 10 fives

In [118]:
array_of_fives = np.ones(10)*5
print(array_of_fives)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


5: Create an array of the integers from 10 to 50

In [119]:
arr = np.arange(10,51)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

6: Create an array of all the even integers from 10 to 50

In [120]:
arr_of_even_integers = np.arange(10,51,2)
arr_of_even_integers

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

7: Create a 3x3 matrix with values ranging from 0 to 8

In [121]:
matrix = np.arange(0,9).reshape(3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

8: Create a 3x3 identity matrix

In [122]:
matrix = np.identity(3)
matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

9: Use NumPy to generate a random number between 0 and 1

In [123]:
from numpy import random 
rand_num = random.rand(1)
print(rand_num)

[0.41606949]


10:Use NumPy to generate an array of 25 random numbers sampled from a standard
normal distribution

In [124]:
import numpy as np
rand_num1 = np.random.normal(0,1,25)
print("25 random numbers from a standard normal distribution:")
rand_num1

25 random numbers from a standard normal distribution:


array([-1.18856238,  0.86831482, -0.26230742, -1.47049221,  0.07050011,
        1.17070874,  1.06949334, -0.31740473,  0.00359866,  0.14587214,
        1.69469737,  1.55755912,  1.25122353, -0.65072679,  0.25282629,
        0.56538707, -1.01247697, -0.80881346,  0.92467773, -0.58308364,
       -1.0254151 , -0.09086651,  0.73084079,  0.30396082,  0.1991885 ])

11: Create an array of 20 linearly spaced points between 0 and 1:

In [125]:
rand_num1 = np.linspace(0,1,20)
print("20 linear numbers between 0 and 1:")
rand_num1

20 linear numbers between 0 and 1:


array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

Perform Numpy Indexing and Selection using the matrix generated using the code
below:

In [126]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

12: Write the code snippet such that the output is as follows from the matrix mat
array([[12, 13, 14, 15],
[17, 18, 19, 20],
[22, 23, 24, 25]])

In [127]:
mat[2:,1:]


array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

13: Write the code snippet such that the output is as follows from the matrix mat
20

In [128]:
mat[-2,-1]


20

14: Write the code snippet such that the output is as follows from the matrix mat
array([[ 2],
[ 7],
[12]])

In [129]:
mat[0:-2,1]

array([ 2,  7, 12])

15: Write the code snippet such that the output is as follows from the matrix mat
array([21, 22, 23, 24, 25])

In [130]:
mat[-1:]

array([[21, 22, 23, 24, 25]])

16:Get the sum of all the values in the mat

17:Get the standard deviation of the values in the mat

18:Get the sum of all the columns on the mat

In [131]:
sum_mat=mat.sum()
print("sum of all the values in matrix mat is", sum_mat, "\n")

#std_dev_mat= mat.std()
std_dev_mat= np.std(mat)
print("std_dev of all the values in matrix mat is", std_dev_mat, "\n")

column_sum= mat.sum(axis=0)
print("sum of all the column values", column_sum)



sum of all the values in matrix mat is 325 

std_dev of all the values in matrix mat is 7.211102550927978 

sum of all the column values [55 60 65 70 75]


19:Import pandas and read in the Ecommerce Purchases csv file and set it to a
DataFrame called ecom

In [132]:
import pandas as pd
from google.colab import files
#uploaded = files.upload()

20: Print the head of the DataFrame.

21: How many rows and columns are there?

In [133]:
ecom = pd.read_csv("/content/drive/MyDrive/Multimedia Systems/Ecommerce Purchases.csv")
print("The head of the dataframe ---ecom--- is \n ")
ecom.head()

The head of the dataframe ---ecom--- is 
 


Address    Lot AM or PM  \
0  16629 Pace Camp Apt. 448\nAlexisborough, NE 77...  46 in       PM   
1  9374 Jasmine Spurs Suite 508\nSouth John, TN 8...  28 rn       PM   
2                   Unit 0065 Box 5052\nDPO AP 27450  94 vE       PM   
3              7780 Julia Fords\nNew Stacy, WA 45798  36 vm       PM   
4  23012 Munoz Drive Suite 337\nNew Cynthia, TX 5...  20 IE       AM   

                                        Browser Info  \
0  Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...   
1  Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...   
2  Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...   
3  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_0 ...   
4  Opera/9.58.(X11; Linux x86_64; it-IT) Presto/2...   

                           Company   Credit Card CC Exp Date  \
0                  Martinez-Herman  6.011930e+15      Feb-20   
1  Fletcher, Richards and Whitaker  3.337760e+15      Nov-18   
2       Simpson, Williams and Pham  6.759580e+11      Aug-19   
3  Williams, Marshall and Buchanan  6.010000e+15      Feb-24   
4        Brown, Watson and Andrews  6.011460e+15      Oct-25   

   CC Security Code                  CC Provider  \
0               900                 JCB 16 digit   
1               561                   Mastercard   
2               699                 JCB 16 digit   
3               384                     Discover   
4               678  Diners Club / Carte Blanche   

                            Email                                     Job  \
0               pdunlap@yahoo.com  Scientist, product/process development   
1              anthony41@reed.com                       Drilling engineer   
2  amymiller@morales-harrison.com                Customer service manager   
3     brent16@olson-robinson.info                       Drilling engineer   
4     christopherwright@gmail.com                             Fine artist   

        IP Address Language  Purchase Price  
0  149.146.147.205       el           98.14  
1     15.160.41.51       fr           70.73  
2   132.207.160.22       de            0.95  
3     30.250.74.19       es           78.04  
4     24.140.33.94       es           77.82

22: What is the average Purchase Price?

In [134]:
ecom['Purchase Price'].mean()

50.347302

23: What were the highest and lowest purchase prices?

In [135]:
max_value= ecom['Purchase Price'].max()
print("max value is",max_value, "\n")

min_value= ecom['Purchase Price'].min()
print("min value is", min_value)

max value is 99.99 

min value is 0.0


24: How many people have English 'en' as their Language of choice on the website?

In [136]:
df = ecom[ecom['Language'] == 'en']
print(len(df))

1098


25: How many people have the job title of "Lawyer"?

In [137]:
df = ecom[ecom['Job'] == 'Lawyer']
print(len(df))

30


26: How many people made the purchase during the AM, and how many people
made the purchase during PM?

In [138]:
df = ecom[ecom['AM or PM'] == 'AM']
print("People made purchases during AM")
print(len(df))

print("People made purchases during PM")
df = ecom[ecom['AM or PM'] == 'PM']
print(len(df))

People made purchases during AM
4932
People made purchases during PM
5068


27: What are the 5 most common Job Titles?

In [139]:
ecom.groupby(['Job']).size().sort_values(ascending=False).head(5) 

Job
Interior and spatial designer        31
Lawyer                               30
Social researcher                    28
Designer, jewellery                  27
Research officer, political party    27
dtype: int64

28: Someone made a purchase that came from Lot: "90 WT" what was the Purchase
Price for this transaction?

In [140]:
print(ecom[ecom['Lot'] == '90 WT']['Purchase Price'].values[0])

75.1


29: What is the email of the person with the following Credit Card Number:
6011930000000000.0

In [141]:
print(ecom[ecom['Credit Card'] == 6011930000000000.0]['Email'])

0                   pdunlap@yahoo.com
898                 qdorsey@yahoo.com
1027            woodsalison@yahoo.com
1964            hannanicole@mills.com
2126            hooverdavid@yahoo.com
2149       reynoldsjonathan@brown.com
2444              ortizrobert@ho.info
2755               thomas10@yahoo.com
4328    johnfrederick@mills-baker.com
6662            clarksharon@gmail.com
7640           hoffmanperry@yahoo.com
8951          yrios@bryant-lawson.com
Name: Email, dtype: object


 30: How many people have American Express as their Credit Card Provider *and
made a purchase above $95?

In [142]:
print(len(ecom[(ecom['CC Provider'] == 'American Express') & (ecom['Purchase Price'] > 95)]))

39


31: How many people have a credit card that expires in 2025?

In [143]:
count = 0
for i in range(len(ecom)):
    expDate = ecom.loc[i, "CC Exp Date"].split('-')
    if expDate[1] == '25':
      count = count + 1
print(count)

1033


32: What are the top 5 most popular email providers/hosts (e.g., gmail.com,
yahoo.com, etc...)?


In [144]:
df = pd.DataFrame(columns=['provider'])
for i in range(len(ecom)):
    email = ecom.loc[i, "Email"].split('@')
    df.loc[i] = [email[1]] 
print(df.groupby(['provider']).size().sort_values(ascending=False).head(5))
    

provider
hotmail.com     1638
yahoo.com       1616
gmail.com       1605
smith.com         42
williams.com      37
dtype: int64
